version: '3.0'

services:
  grafana:
    container_name: 'positiveviking-ycmonitoring-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=positiveviking-ycmonitoring-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/positiveviking-ycmonitoring-datasource
      - ./provisioning:/etc/grafana/provisioning
      - /etc/ssl/certs/:/etc/ssl/certs/
